spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_orchestrator?options=-c%20TimeZone=UTC
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    dynamic: true

server:
  port: 8080
logging:
  level:
    org:
      springframework:
        amqp: DEBUG
        rabbit: DEBUG